/* Quire Clinical Data — local-only de-identified dataset workspace */
(function(){
const KEY='quire:clinical-data:v1',$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
function pid(){return window.QuireStore?.getActiveProjectId?.()||'default'}function all(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}function saveAll(x){localStorage.setItem(KEY,JSON.stringify(x));render()}
function rows(){return all().filter(x=>x.projectId===pid())}
function parseCSV(text){const lines=text.replace(/\r/g,'').split('\n').filter(x=>x.trim());if(!lines.length)return{headers:[],rows:[]};const split=line=>{let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out};const headers=split(lines[0]);return{headers,rows:lines.slice(1).map(split).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}}
const risky=/\b(name|first.?name|last.?name|surname|patient.?id|hospital.?id|id.?number|mrn|medical.?record|dob|date.?of.?birth|address|phone|mobile|email|passport|national.?id)\b/i;
function variableSummary(ds){return ds.headers.map(h=>{const vals=ds.rows.map(r=>r[h]).filter(v=>v!==''),nums=vals.map(Number).filter(Number.isFinite),unique=new Set(vals).size;return{name:h,n:vals.length,missing:ds.rows.length-vals.length,unique,type:nums.length===vals.length&&vals.length?'numeric':'text',min:nums.length?Math.min(...nums):null,max:nums.length?Math.max(...nums):null,mean:nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null}})}
function render(){const d=rows();$('clinicalDatasetCount').textContent=d.length;$('clinicalRowCount').textContent=d.reduce((n,x)=>n+x.rows.length,0);$('clinicalVariableCount').textContent=d.reduce((n,x)=>n+x.headers.length,0);const state=window.QuireStore?.getState?.()||{};$('clinicalFindingCount').textContent=(state.analysisItems||[]).filter(x=>x.projectId===pid()&&x.kind==='clinical_finding').length;const m=$('clinicalDatasetList');if(!m)return;m.innerHTML=d.length?d.map(x=>'<article class="clinical-dataset-card"><div><span class="eyebrow">CLINICAL DATASET</span><h3>'+esc(x.name)+'</h3><p>'+esc([x.source,x.period].filter(Boolean).join(' · ')||'Source not described')+'</p><small>'+x.rows.length+' records · '+x.headers.length+' variables · imported '+esc(x.created.slice(0,10))+'</small></div><div><button class="soft-btn" data-open-clinical="'+x.id+'">Explore data</button><button class="text-btn danger-text" data-delete-clinical="'+x.id+'">Remove</button></div></article>').join(''):'<div class="analysis-empty"><strong>No clinical datasets yet</strong><small>Add a de-identified CSV when you are ready. Published papers remain in Research; your clinical data stays separate here.</small></div>';m.querySelectorAll('[data-open-clinical]').forEach(b=>b.onclick=()=>openDetail(b.dataset.openClinical));m.querySelectorAll('[data-delete-clinical]').forEach(b=>b.onclick=()=>{if(confirm('Remove this local clinical dataset from Quire?'))saveAll(all().filter(x=>x.id!==b.dataset.deleteClinical))})}
function openImport(){['clinicalDatasetName','clinicalDatasetSource','clinicalDatasetPeriod','clinicalDatasetPurpose','clinicalDatasetNotes'].forEach(id=>$(id).value='');$('clinicalDeidentifiedConfirm').checked=false;$('clinicalCsvInput').value='';$('clinicalImportStatus').textContent='';$('clinicalDatasetModal').hidden=false}
function closeImport(){$('clinicalDatasetModal').hidden=true}
async function importData(){const file=$('clinicalCsvInput').files[0],status=$('clinicalImportStatus');if(!$('clinicalDatasetName').value.trim()){status.textContent='Give the dataset a name.';return}if(!$('clinicalDeidentifiedConfirm').checked){status.textContent='Confirm de-identification before importing.';return}if(!file){status.textContent='Choose a CSV file.';return}const parsed=parseCSV(await file.text());if(!parsed.headers.length){status.textContent='No CSV columns were found.';return}const flagged=parsed.headers.filter(h=>risky.test(h));if(flagged.length){status.textContent='Import stopped: possible identifying columns detected — '+flagged.join(', ')+'. Remove or rename only after confirming they contain no identifiers.';return}const item={id:'clinical_'+Date.now(),projectId:pid(),name:$('clinicalDatasetName').value.trim(),source:$('clinicalDatasetSource').value.trim(),period:$('clinicalDatasetPeriod').value.trim(),purpose:$('clinicalDatasetPurpose').value.trim(),notes:$('clinicalDatasetNotes').value.trim(),headers:parsed.headers,rows:parsed.rows,created:new Date().toISOString(),localOnly:true};const x=all();x.push(item);localStorage.setItem(KEY,JSON.stringify(x));closeImport();render()}
function openDetail(id){const d=all().find(x=>x.id===id);if(!d)return;$('clinicalDetailTitle').textContent=d.name;const vars=variableSummary(d);$('clinicalDetailBody').innerHTML='<div class="clinical-detail-meta"><strong>'+d.rows.length+' records · '+d.headers.length+' variables</strong><p>'+esc(d.purpose||'No thesis relationship recorded.')+'</p></div><div class="clinical-variable-table"><div class="clinical-variable-row head"><b>Variable</b><b>Type</b><b>Complete</b><b>Summary</b></div>'+vars.map(v=>'<div class="clinical-variable-row"><strong>'+esc(v.name)+'</strong><span>'+v.type+'</span><span>'+v.n+'/'+d.rows.length+'</span><span>'+(v.type==='numeric'?'mean '+v.mean.toFixed(2)+' · range '+v.min+'–'+v.max:v.unique+' unique values')+'</span></div>').join('')+'</div><div class="clinical-preview-note"><strong>Data preview intentionally limited</strong><p>Quire summarises variables here rather than displaying a patient-level table. Use aggregate findings for thesis interpretation.</p></div><label class="field wide"><span>Save an aggregate finding / observation</span><textarea id="clinicalFindingText" rows="3" placeholder="e.g. 42% of records… Include denominators and caveats where appropriate."></textarea></label><button class="primary-btn" id="saveClinicalFindingBtn">Save finding for analysis</button>';$('clinicalDatasetDetailModal').hidden=false;$('saveClinicalFindingBtn').onclick=()=>{const t=$('clinicalFindingText').value.trim();if(!t)return;window.QuireStore.addAnalysisItem({kind:'clinical_finding',title:t,status:'draft',payload:{datasetId:d.id,datasetName:d.name,sourceType:'clinical_data',interpretation:t,aggregateOnly:true}});$('clinicalFindingText').value='';render()}}
function bind(){$('newClinicalDatasetBtn')?.addEventListener('click',openImport);$('closeClinicalDatasetModal')?.addEventListener('click',closeImport);$('cancelClinicalDataset')?.addEventListener('click',closeImport);$('saveClinicalDataset')?.addEventListener('click',importData);$('closeClinicalDetailModal')?.addEventListener('click',()=>{$('clinicalDatasetDetailModal').hidden=true});window.addEventListener('quire:project-switched',render);render()}
document.addEventListener('DOMContentLoaded',bind);window.QuireClinicalData={render,openImport};
})();